import { Quote } from "../quotable";

const myDate = new Date("2021-10-03");

export const seedQuotes: Quote[] = [
  {
    _id: "humorcode",
    content: "Code is like humor. When you have to explain it, it’s bad.",
    author: "Cory House",
    authorSlug: "cory-house",
    length: 58,
    tags: ["programming", "code", "funny"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "anyfool",
    content:
      "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    author: "Martin Fowler",
    authorSlug: "martin-fowler",
    length: 111,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "firstthen",
    content: "First, solve the problem. Then, write the code.",
    author: "John Johnson",
    authorSlug: "john-johnson",
    length: 111,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "experiencemistakes",
    content: "Experience is the name everyone gives to their mistakes.",
    author: "Oscar Wilde",
    authorSlug: "oscar-wilde",
    length: 111,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "irreplaceable",
    content: "In order to be irreplaceable, one must always be different",
    author: "Coco Chanel",
    authorSlug: "coco-chanel",
    length: 58,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "javascriptcarpet",
    content: "Java is to JavaScript what car is to Carpet.",
    author: "Chris Heilmann",
    authorSlug: "chris-heilmann",
    length: 44,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "knowledgepower",
    content: "Knowledge is power.",
    author: "Francis Bacon",
    authorSlug: "francis-bacon",
    length: 19,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "bedmondaydebuggingweek",
    content:
      "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.",
    author: "Dan Salomon",
    authorSlug: "dan-salomon",
    length: 110,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "perfectionnotadd",
    content:
      "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.",
    author: "Antoine de Saint-Exupery",
    authorSlug: "antoine-de saint-exupery",
    length: 113,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "rubbishphpantastic",
    content: "Ruby is rubbish! PHP is phpantastic!",
    author: "Nikita Popov",
    authorSlug: "nikita-popov",
    length: 36,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "fixcausenotsymptom",
    content: "Fix the cause, not the symptom.",
    author: "Steve Maguire",
    authorSlug: "steve-maguire",
    length: 31,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "optimismfeedback",
    content:
      "Optimism is an occupational hazard of programming: feedback is the treatment.",
    author: "Kent Beck",
    authorSlug: "kent-beck",
    length: 77,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "iterativedevelopment",
    content:
      "When to use iterative development? You should use iterative development only on projects that you want to succeed.",
    author: "Martin Fowler",
    authorSlug: "martin-fowler",
    length: 114,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "simplicityefficiency",
    content: "Simplicity is the soul of efficiency.",
    author: "Austin Freeman",
    authorSlug: "austin-freeman",
    length: 37,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "reusableusable",
    content: "Before software can be reusable it first has to be usable.",
    author: "Ralph Johnson",
    authorSlug: "ralph-johnson",
    length: 58,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
  {
    _id: "workrightfast",
    content: "Make it work, make it right, make it fast.",
    author: "Kent Beck",
    authorSlug: "kent-beck",
    length: 42,
    tags: ["programming", "code"],
    dateAdded: myDate,
    dateModified: myDate,
  },
];
